In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
# from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error

In [2]:
df = pd.read_csv("SeoulBikeData.csv")
df.head()

,Date,Rented Bike Count,Hour,Temperature(�C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(�C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day
0,01/12/2017,254,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
1,01/12/2017,204,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
2,01/12/2017,173,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,Winter,No Holiday,Yes
3,01/12/2017,107,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
4,01/12/2017,78,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,Winter,No Holiday,Yes

In [3]:
y = df["Rented Bike Count"]
x = df.loc[:, df.columns != "Rented Bike Count"]

In [4]:
y.head()

0    254
1    204
2    173
3    107
4     78
Name: Rented Bike Count, dtype: int64

In [5]:
x.head()

,Date,Hour,Temperature(�C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(�C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day
0,01/12/2017,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
1,01/12/2017,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
2,01/12/2017,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,Winter,No Holiday,Yes
3,01/12/2017,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
4,01/12/2017,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,Winter,No Holiday,Yes

In [6]:
from sklearn.preprocessing import LabelEncoder

number = LabelEncoder()
x["Date"] = number.fit_transform(x["Date"].astype("str"))

x.head()

<ipython-input-6-4902686696fe>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x["Date"] = number.fit_transform(x["Date"].astype("str"))

,Date,Hour,Temperature(�C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(�C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day
0,11,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
1,11,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
2,11,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,Winter,No Holiday,Yes
3,11,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
4,11,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,Winter,No Holiday,Yes

In [7]:
number = LabelEncoder()
x["Seasons"] = number.fit_transform(x["Seasons"].astype("str"))

x.head()

<ipython-input-7-067cfdab8add>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x["Seasons"] = number.fit_transform(x["Seasons"].astype("str"))

,Date,Hour,Temperature(�C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(�C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day
0,11,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,3,No Holiday,Yes
1,11,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,3,No Holiday,Yes
2,11,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,3,No Holiday,Yes
3,11,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,3,No Holiday,Yes
4,11,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,3,No Holiday,Yes

In [8]:
number = LabelEncoder()
x["Holiday"] = number.fit_transform(x["Holiday"].astype("str"))

x.head()

<ipython-input-8-b2aedff81a56>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x["Holiday"] = number.fit_transform(x["Holiday"].astype("str"))

,Date,Hour,Temperature(�C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(�C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day
0,11,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,3,1,Yes
1,11,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,3,1,Yes
2,11,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,3,1,Yes
3,11,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,3,1,Yes
4,11,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,3,1,Yes

In [9]:
number = LabelEncoder()
x["Functioning Day"] = number.fit_transform(x["Functioning Day"].astype("str"))

x.head()

<ipython-input-9-259e13336bab>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x["Functioning Day"] = number.fit_transform(x["Functioning Day"].astype("str"))

,Date,Hour,Temperature(�C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(�C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day
0,11,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,3,1,1
1,11,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,3,1,1
2,11,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,3,1,1
3,11,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,3,1,1
4,11,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,3,1,1

In [10]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [11]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [12]:
RentedBikeCount_pred = model.predict(X_test)

In [13]:
#coefficients

print("Coefficients: \n", model.coef_)

print("Intercept: \n", model.intercept_)

#mean squared error

print("Mean squared error: %.2f"
      % mean_squared_error(y_test, RentedBikeCount_pred))

#coefficient of determination: 1 is perfect prediction

print("Coefficient of determination: %.2f"
      % r2_score(y_test, RentedBikeCount_pred))

#mean absolute error

print("Mean absolute error: %.2f"
     %mean_absolute_error(y_test, RentedBikeCount_pred))

Coefficients:
 [-7.30906243e-02  2.70729028e+01  1.16406433e+01 -1.31565031e+01
  2.11674760e+01  7.00421596e-03  1.96970828e+01 -8.47056621e+01
 -5.77723014e+01  4.37174968e+01 -1.02962418e+02  1.10315986e+02
  9.57209981e+02]
Intercept:
 77.66144088235217
Mean squared error: 165559.89
Coefficient of determination: 0.56
Mean absolute error: 306.73

In [14]:
mse = mean_squared_error(y_test, RentedBikeCount_pred)
rmse = np.sqrt(mse)
print("RMSE: %.2f" %rmse)

RMSE: 406.89